"""agrega tabla consultas_limitadas

Revision ID: 0e31ac78b23f
Revises: d357b6c168d1
Create Date: 2026-09-11 20:34:15.327128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e31ac78b23f'
down_revision = 'd357b6c168d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultas_limitadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=150), nullable=False),
    sa.Column('momento', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consultas_limitadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultas_limitadas_clave'), ['clave'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultas_limitadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultas_limitadas_clave'))

    op.drop_table('consultas_limitadas')
    # ### end Alembic commands ###
