"""Estado inicial

Revision ID: 1321d039f458
Revises: 
Create Date: 2026-09-05 16:13:03.713739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1321d039f458'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('anios', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ejercicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('cuota', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_asamblea', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('cerrado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('aportantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('anio', sa.String(length=5), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aportantes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aportantes_dni'), ['dni'], unique=True)

    op.create_table('fondos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('saldo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_grupales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_seguimiento', sa.String(length=20), nullable=True),
    sa.Column('codigo_transaccion', sa.String(length=100), nullable=False),
    sa.Column('importe_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comprobante_nombre', sa.String(length=255), nullable=True),
    sa.Column('hash_comprobante', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_transaccion')
    )
    with op.batch_alter_table('pagos_grupales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_grupales_codigo_seguimiento'), ['codigo_seguimiento'], unique=True)
        batch_op.create_index(batch_op.f('ix_pagos_grupales_hash_comprobante'), ['hash_comprobante'], unique=False)

    op.create_table('solicitudes_fondo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_seguimiento', sa.String(length=20), nullable=True),
    sa.Column('responsable', sa.String(length=120), nullable=False),
    sa.Column('contacto', sa.String(length=120), nullable=False),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.Column('curso', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('importe_estimado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_estimada', sa.Date(), nullable=True),
    sa.Column('justificacion', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('resuelta_por_id', sa.Integer(), nullable=True),
    sa.Column('fecha_resolucion', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['resuelta_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_fondo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_fondo_codigo_seguimiento'), ['codigo_seguimiento'], unique=True)

    op.create_table('movimientos_fondo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fondo_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('saldo_anterior', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('saldo_resultante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fondo_id'], ['fondos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_seguimiento', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('importe', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('medio_pago', sa.String(length=50), nullable=True),
    sa.Column('codigo_transaccion', sa.String(length=100), nullable=True),
    sa.Column('hash_comprobante', sa.String(length=64), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('comprobante_nombre', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('numero_recibo', sa.String(length=20), nullable=True),
    sa.Column('serie_recibo', sa.String(length=5), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('verificado_por_id', sa.Integer(), nullable=True),
    sa.Column('cuit', sa.String(length=13), nullable=True),
    sa.Column('solicita_libreta', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('aportante_id', sa.Integer(), nullable=False),
    sa.Column('fondo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ejercicio_id', sa.Integer(), nullable=True),
    sa.Column('pago_grupal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aportante_id'], ['aportantes.id'], ),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.ForeignKeyConstraint(['fondo_id'], ['fondos.id'], ),
    sa.ForeignKeyConstraint(['pago_grupal_id'], ['pagos_grupales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['verificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_transaccion')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagos_codigo_seguimiento'), ['codigo_seguimiento'], unique=True)
        batch_op.create_index(batch_op.f('ix_pagos_hash_comprobante'), ['hash_comprobante'], unique=False)

    op.create_table('pagos_grupales_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pago_grupal_id', sa.Integer(), nullable=False),
    sa.Column('aportante_id', sa.Integer(), nullable=False),
    sa.Column('monto_asignado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('solicita_libreta', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aportante_id'], ['aportantes.id'], ),
    sa.ForeignKeyConstraint(['pago_grupal_id'], ['pagos_grupales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saldos_aportantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aportante_id', sa.Integer(), nullable=False),
    sa.Column('ejercicio_id', sa.Integer(), nullable=False),
    sa.Column('cuota_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pagado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('saldo_pendiente', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('libreta_entregada', sa.Boolean(), nullable=True),
    sa.Column('fecha_libreta', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aportante_id'], ['aportantes.id'], ),
    sa.ForeignKeyConstraint(['ejercicio_id'], ['ejercicios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aportante_id', 'ejercicio_id', name='uq_saldo_aportante_ejercicio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldos_aportantes')
    op.drop_table('pagos_grupales_detalle')
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_hash_comprobante'))
        batch_op.drop_index(batch_op.f('ix_pagos_codigo_seguimiento'))

    op.drop_table('pagos')
    op.drop_table('movimientos_fondo')
    with op.batch_alter_table('solicitudes_fondo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_fondo_codigo_seguimiento'))

    op.drop_table('solicitudes_fondo')
    with op.batch_alter_table('pagos_grupales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagos_grupales_hash_comprobante'))
        batch_op.drop_index(batch_op.f('ix_pagos_grupales_codigo_seguimiento'))

    op.drop_table('pagos_grupales')
    op.drop_table('fondos')
    with op.batch_alter_table('aportantes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aportantes_dni'))

    op.drop_table('aportantes')
    op.drop_table('usuarios')
    op.drop_table('ejercicios')
    op.drop_table('carreras')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
