"""Restricciones de unicidad en fondos y ejercicios

Revision ID: 8a078e83d673
Revises: f31aa8197299
Create Date: 2026-09-05 16:40:10.334242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a078e83d673'
down_revision = 'f31aa8197299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.create_index('uq_ejercicio_vigente', ['activo'], unique=True, sqlite_where=sa.text('activo = 1 AND cerrado = 0'), postgresql_where=sa.text('activo = true AND cerrado = false'))

    with op.batch_alter_table('fondos', schema=None) as batch_op:
        batch_op.create_index('uq_fondos_capital_activo', ['tipo'], unique=True, sqlite_where=sa.text("tipo = 'capital' AND activo = 1"), postgresql_where=sa.text("tipo = 'capital' AND activo = true"))
        batch_op.create_index('uq_fondos_carrera_tipo', ['carrera_id', 'tipo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fondos', schema=None) as batch_op:
        batch_op.drop_index('uq_fondos_carrera_tipo')
        batch_op.drop_index('uq_fondos_capital_activo', sqlite_where=sa.text("tipo = 'capital' AND activo = 1"), postgresql_where=sa.text("tipo = 'capital' AND activo = true"))

    with op.batch_alter_table('ejercicios', schema=None) as batch_op:
        batch_op.drop_index('uq_ejercicio_vigente', sqlite_where=sa.text('activo = 1 AND cerrado = 0'), postgresql_where=sa.text('activo = true AND cerrado = false'))

    # ### end Alembic commands ###
