"""carrera_id obligatorio en solicitudes_fondo

Revision ID: d357b6c168d1
Revises: 909b3621ff6e
Create Date: 2026-09-10 00:18:38.793407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd357b6c168d1'
down_revision = '909b3621ff6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_fondo', schema=None) as batch_op:
        batch_op.alter_column('carrera_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_fondo', schema=None) as batch_op:
        batch_op.alter_column('carrera_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
