"""Elimina saldos_aportantes.cuota_total

Revision ID: f31aa8197299
Revises: 1321d039f458
Create Date: 2026-09-05 16:28:27.943683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31aa8197299'
down_revision = '1321d039f458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos_aportantes', schema=None) as batch_op:
        batch_op.drop_column('cuota_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saldos_aportantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuota_total', sa.NUMERIC(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
